### ISSUE TITLE
When loading cams, if one of the cams is offline/not recording, whole card doesn't load. 

### ISSUE THREAD

**Issue by papacrown** [custom-cards/surveillance-card#1]
I have a few Canary cams that don't record while offline, but the rest of my setup is with Unifi G3's. The Unifi's wouldn't show up if the Canarys were in my config and weren't recording.

**Comment by niemyjski** [comment]
I have multiple unifi cameras and I haven't seen this issue even when one camera is offline. Please let me know if you get any errors (and attach stack traces) and we'll look into it.
