### ISSUE TITLE
custom element doesn't exist

### ISSUE THREAD

**Issue by s0c1** [custom-cards/surveillance-card#10]
lit-element has moved to:
https://unpkg-gcp.firebaseapp.com/@polymer/lit-element@0.5.2/lit-element.js?module

**Comment by IIIdefconIII** [comment]
same here, seems that all custom cards need a update or so,

**Comment by ezraholm50** [comment]
Still wont work, after changing, restarting. Any advise? Another card "power wheel" did work after changing..

**Comment by s0c1** [comment]
You have to clear your browser cache for this change to appear. Also, I did a contribute a pull request, so you can see the source that worked for me.

**Comment by PlayedIn** [comment]
> You have to clear your browser cache for this change to appear. Also, I did a contribute a pull request, so you can see the source that worked for me.

Are you saying this card is broken until the code is changed?  First time installer here, and also receiving "custom element doesn't exist".

**Comment by chuckweinberger** [comment]
@s0c1's pull requested worked for me for a few months, but now I'm getting the following js error: `:8123/local/surveillance-card.js?v=2:1` Uncaught SyntaxError: Unexpected token {
which is the first line of the import statement.

**Comment by prasket** [comment]
I did a little digging and found this message at the old source in npmjs 

> @polymer/lit-element has moved to lit-element. Please uninstall this package and install lit-element. See https://www.polymer-project.org/blog/2019-01-11-lit-element-rc

New location is here: [https://www.npmjs.com/package/lit-element](https://www.npmjs.com/package/lit-element)

I tried just subbing out locations and for new versions as a first go but didnt work. :(

**Comment by cagnulein** [comment]
anyone has a solution?

**Comment by s0c1** [comment]
I pulled this out and switched to the plain Camera element. If you use the still_image_url with a fast refresh time (1 second), it works like a champ in stock HA.

**Comment by niemyjski** [comment]
I'm not seeing this issue, can someone please let me know how to reproduce this issue. I'm not having any issues with this component and I have unifi, nest and amcrest cameras.

**Comment by niemyjski** [comment]
Fixed
