### ISSUE TITLE
Tap Action, Hold Action

### ISSUE THREAD

**Issue by sea3pea0** [custom-cards/surveillance-card#12]
It would be great if we could set a tap action for the card. That way for ptz cameras a click on the card could change the ptz preset for the camera.

I have done this already with the picture glances card. I have all my camera's presets synced with a input_number for each camera. When input_number is changed it directs the camera to change preset position. So on the picture glances card, when the card is clicked it calls input_number.increment to change to the next preset. When it gets to the last preset + 1, I have it set to go back to the first preset.

Great card though, it looks really nice!

**Comment by Korte68** [comment]
+1 
I also would like to set action on tap on the picture...

**Comment by niemyjski** [comment]
If you want to submit a pr for this, I'll review and accept it! If there are no takers I'll be closing this issue in the near future.
