### ISSUE TITLE
**Last updated 12 months ago**

### ISSUE THREAD

**Issue by VarenDerpsAround** [custom-cards/surveillance-card#20]
I'm going to reverse course and uninstall this in the state it is currently in. I tried to get the card to work, it just gives me UI errors and broken images. Pass. Enclosed are some of my screen shots. 
![image](https://user-images.githubusercontent.com/58420778/71898546-39b2fc80-311f-11ea-95d8-31ecc2ef7ffb.png)
![image](https://user-images.githubusercontent.com/58420778/71898586-54857100-311f-11ea-8b45-6f1e15186211.png)

please advise as to my next course of action, but seeing as no issues in this have been closed in over a year, I'm going to guess this is just going to be crumbs for anyone else looking into this custom card.

**Comment by jysaloma** [comment]
Having the same issues. From the logs
ERROR (MainThread) [frontend.js.latest.202003181] https://ha.xxxx.xxx/community_plugin/surveillance-card/surveillance-card.js:10:25TypeError: this._hass.states[currentCamera] is undefined
WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.

Any alternatives available if this on will not be maintaned?
