### ISSUE TITLE
Add HACS Support

### ISSUE THREAD

**Issue by niemyjski** [custom-cards/surveillance-card#23]
Looks like the directory structure just needs to be changed for this:

https://github.com/hacs/integration/issues/1062

**Comment by niemyjski** [comment]
@jeradM, @ciotlosm, @Gluwc, @iantrich, @maykar Can we get some help/people (including myself) added to maintainers of this repo / org. I'll try my best to help fix major issues (time is limited but any time is better than nothing), review pr's and merge them.

**Comment by iantrich** [comment]
If anyone submits PRs I can merge them but I don't plan on doing anything beyond that.

**Comment by niemyjski** [comment]
@iantrich I submitted a pr: #25

**Comment by iantrich** [comment]
Does this card even work on newer installs?

**Comment by niemyjski** [comment]
Yes I’m using it on the latest version
