### ISSUE TITLE
Feature request: Multiple motion entities

### ISSUE THREAD

**Issue by cristimi** [custom-cards/surveillance-card#26]
Really nice card. Is it possible to add multiple motion entities ? I have a camera which is watching 3 different doors each with its sensor so would be nice to be able to add all 3.

**Comment by ielbury** [comment]
I will add, nice card, I have multiple sources of motion, some PIR and some from MotionEye in an area. Would be awesome to have multiple motion entities.

**Comment by niemyjski** [comment]
I just made this possible with #28 by adding this metadata to the camera model. But more work has to be done here.. Would you submit a pr for this based on #28 when it's merged in. It should just be a matter of updating the markup

**Comment by whoisdecoy** [comment]
Could be solved by grouping sensors and using the group as sensor instead?

**Comment by niemyjski** [comment]
I think that would work. Can you try it and let us know.

**Comment by whoisdecoy** [comment]
Sorry - I don't use this anymore and when I did I didn't use the motion sensors. Just had the idea when browsing.
