### ISSUE TITLE
Main camera stream not present at the beginning + Login failed

### ISSUE THREAD

**Issue by Luke95vl** [custom-cards/surveillance-card#29]
after updating to the latest version the image of the main camera does not appear, the broken image icon is present, while the mini thumbails work regularly. If I wait 15 seconds the image appears but at every page refresh the problem persists.
In addition, every time I try to access the surveillance screen I receive a failed login notification from the IP of the device I am using. In the logs is reported

```
Logger: homeassistant.components.http.ban
Source: components / http / ban.py: 75
```

**Comment by hsolberg** [comment]
I get the same exact problem. I think it might be related to this perhaps: https://github.com/custom-cards/surveillance-card/issues/22#issuecomment-654212714

**Comment by cben0ist** [comment]
Same issue for me too.

**Comment by niemyjski** [comment]
Is it due to the main image not having an access token? I've seen this happen once but haven't been able to track it down? Other than this is it working ok? We should be able to do some really cool stuff now that we have state and info on every camera.

**Comment by Luke95vl** [comment]
I don't know if it needs access, my knowledge is limited in this field, the main image works after 10/15 seconds that I have accessed the page, the rest works all

**Comment by niemyjski** [comment]
Sorry for taking so long to respond I've been pretty busy but tried to see if I can see this behavior, but haven't really had time to track it down. I wonder if it has to do with the camera_stream_proxy taking a little bit to get ready.

**Comment by niemyjski** [comment]
It would be a huge help if someone could dig into this.

**Comment by niemyjski** [comment]
Has anyone had time to look into this?  When I first hit it, it was due to the camera proxy stream not having an access token.

**Comment by RoldyBuffalo** [comment]
Heya, I seem to have the same issue. I'll edit this reply to include logs, unless you happen to reply before I hit enter.

**Comment by niemyjski** [comment]
Seems like the token is invalid that we get back from the api. We are just using the access token that's provided in the state attributes. These bans are not idea. Can you please see if my latest commit fixes this for you: https://github.com/custom-cards/surveillance-card/commit/a1b1933ef7c1ae025380604dc9884d65243fefb6 If not,  would you mind filing a bug on the HA repo and reference https://github.com/custom-cards/surveillance-card/blob/master/surveillance-card.js#L115-L119

**Comment by lassealfastsen** [comment]
i Have the exact same issue, did anyone fix it?

**Comment by kkellner** [comment]
@niemyjski The master branch seems to have fixed the issue for me.

**Comment by niemyjski** [comment]
Awesome! I'll try and tag a release

**Comment by kkellner** [comment]
I spoke too soon.   The right side (large view) comes up immediately now, however after a view minutes I get banned.  I'll continue testing.

**Comment by kkellner** [comment]
Looks like it has something to do with HA restart --  I have a tablet that has a lovelace view showing view with`surveillance-card`.  When I restart HA, after HA starts I get 1 failed login from the tablet.  Then all seems to be OK.  Since my HA is front-ended with an HA-proxy, all the requests look like they come from the same IP.

I suspect that if I have 5 devices (e.g., many tablets) that all will get 1 failed login each and all 5 devices look like the same IP because of my proxy setup, it will add the IP to the `ip_bans.yaml` file.

This doesn't explain why the IP added up getting banned for me earlier as I only have the 1 tablet and I had 2 chrome tabs open on my laptop to a HA lovelace view that has surveillance-card.   So even if it was 1 failed login per device/tab that would have only been 3 failed logins.

**Comment by kkellner** [comment]
@niemyjski  I believe your change is good for getting a valid stream at first view.  However it doesn't (fully) resolve the login failed issue.  Some interesting discussion on the topic here:

https://community.home-assistant.io/t/wth-are-those-login-attempt-failed/219519/58

**Comment by niemyjski** [comment]
This seems blocked by https://github.com/home-assistant/frontend/issues/3379 which is the core issue. We only use the token that is provided by the HA state.

**Comment by dustins1983** [comment]
Im getting this too, and for me it shifts the whole card to the right, so i have to scroll sideways to see the camera

**Comment by niemyjski** [comment]
I'm going to close this as it seems like it's resolved in core now via the linked frontend issue https://github.com/home-assistant/frontend/issues/3379 Please let me know if this is still an issue. Any help would be greatly appreciated.
