### ISSUE TITLE
[Feature:] Add screenshots

### ISSUE THREAD

**Issue by KTibow** [custom-cards/surveillance-card#30]
Not a big priority issue, just a lot of card docs have them, and I don't know what the "style of a surveillance system" looks like.

**Comment by niemyjski** [comment]
It would be nice to trigger recording or screenshots, not sure how it would work or if it would prompt to save to your computer or just in local storage.

**Comment by KTibow** [comment]
You're right, that's a good idea, although I was thinking of screenshots for the docs (so you can see what it looks like).

**Comment by Kedryn** [comment]
So, still no screenshots?
Do we have to install and configure all, to find out it isn't what we thought?

**Comment by atrv7** [comment]
@niemyjski @KTibow  I am working on adding the screenshot & recording functionalities  I will create a new PR and push my code tomorrow afternoon

**Comment by Kedryn** [comment]
> @niemyjski @KTibow I am working on adding the screenshot & recording functionalities. I will create a new PR and push my code tomorrow afternoon

I think you misunderstood the request.

We are asking screenshots of what this addon looks like, in the in docs, not making screenshots with the surveillance-card

**Comment by atrv7** [comment]
@Kedryn there are 2 issues here. There is already a PR that should resolve your screenshot documentation issue ( #35 ). 

I am working on @niemyjski's suggestion to add screenshot/recording functionalities which @KTibow also agreed would be a nice feature

**Comment by atrv7** [comment]
@niemyjski @KTibow I created a PR to add the snapshot and burst record functionalities to this code base. Take a look and let me know if it is what you envisioned and to let me know if there are better ways of implementing parts of it. Happy to work on it some more if there are things you would like to be done differently
