### ISSUE TITLE
Enhancement request: Use "live" view

### ISSUE THREAD

**Issue by kkellner** [custom-cards/surveillance-card#33]
Enhancement request:

I would like the option to use the "live" (stream) for either thumbnails and/or large image.

This would be similar to the `camera_view: live` property on the picture-entity card.

```
type: picture-entity
entity: camera.blueiris_frontyard_ptz_cam24
camera_view: live
```

Something like this (or maybe would need to be a separate property if `interval` properties are integer only types):

```
type: 'custom:surveillance-card'
thumb_interval: live
update_interval: live
cameras:
   ...
```

**Comment by niemyjski** [comment]
Yeah, I've tried to do this with the camera stream url and it seemed to update not as quick. Would you mind looking into this and submit a pr.

**Comment by niemyjski** [comment]
this was just merged in via a pr!
