### ISSUE TITLE
Surveillance-card: semi not working with HACS

### ISSUE THREAD

**Issue by tommyjlong** [custom-cards/surveillance-card#38]
I use HACS to track and update this card.  When upgrading to 0.0.4 (using HACS), each thumbnail now contains two semi-transparent circles, but I'm not sure what this is all about.  One appears to be for taking a snapshot, and I think the other is for recording.  I'm getting an error in Chrome Inspect saying it can not find record.svg and snapshot.svg.  HACS did not pickup these svg files.  I did download them into the directory where HACS stores the surveillance-card, but this didn't work.  The error seems to be the javascript code expects these files to be located in www(or local)/surveillance-card/ but this is not where HACS keeps the surveillance-card.

**Comment by reefland** [comment]
same issue.  HACS didn't even seem to download the images.  Had to grab them manually.

Thanks for pointing out where they were expected.  For now, this workaround of creating a symlink where it was expected got the images to show up:

```
root@freenas: www # ln -s community/surveillance-card/ .
root@freenas: www # ls -l
total 14
drwxr-xr-x  5 8123  8123   5 Nov 22 14:31 community
drwxr-xr-x  2 8123  8123   3 Feb 13  2020 custom_ui
drwxr-xr-x  3 8123  8123   4 Mar  2  2020 icons
lrwxr-xr-x  1 root  8123  28 Nov 22 14:50 surveillance-card -> community/surveillance-card/
```

**Comment by XoniBlue** [comment]
> same issue. HACS didn't even seem to download the images. Had to grab them manually.
> 
> Thanks for pointing out where they were expected. For now, this workaround of creating a symlink where it was expected got the images to show up:
> 
> ```
> root@freenas: www # ln -s community/surveillance-card/ .
> root@freenas: www # ls -l
> total 14
> drwxr-xr-x  5 8123  8123   5 Nov 22 14:31 community
> drwxr-xr-x  2 8123  8123   3 Feb 13  2020 custom_ui
> drwxr-xr-x  3 8123  8123   4 Mar  2  2020 icons
> lrwxr-xr-x  1 root  8123  28 Nov 22 14:50 surveillance-card -> community/surveillance-card/
> ```

would you mind explaining how you went about doing this?

**Comment by reefland** [comment]
Not sure understand your confusion with the steps above.  The "www" directory is located within your Home Assistant configuration directory.  The `ln -s community/surveillance-card/ .` is what creates the symlink.  The example above was done on a FreeBSD jail where HA is running.  The steps would be identical on Linux.  Hope that helps.

**Comment by johntdyer** [comment]
FWIW when I "reinstall" the this plugin it actually deleted the SVG files.  Put another way I am able to manually download the files using the wget commands per the readme.md and then do a "reinstall" via the add-ons place and the it wil actually deletes the svg files I manually downloaded

**Comment by johntdyer** [comment]
@niemyjski - Any thoughts here ?

**Comment by niemyjski** [comment]
I've seen this too but I haven't had time to look into it. I wonder if there is something excluding svg's from being copied? I would think we would just be using font icons that are built into HA. Can someone submit a pr for this?

**Comment by MisterTFM** [comment]
Same issue, using HACS, it didn't download the *.svg files.
![ScreenHunter 177](https://user-images.githubusercontent.com/74779407/113497195-a017fd80-94cf-11eb-8b6a-e4d290d20017.jpg)

**Comment by niemyjski** [comment]
Can you please submit a pr that resolves this issue

**Comment by niemyjski** [comment]
I just resolved this issue in the latest commit
