### ISSUE TITLE
Surveillance-card not showing up inside a Swipe-Card

### ISSUE THREAD

**Issue by albertorivi** [custom-cards/surveillance-card#40]
home assistant 0.117.6 i didn't know if it's working before.

In case I add the surveillance-card inside a swipe-card on a dashboard the surveillance-card is not showing up on the dashboard.
Some ideas?

here is a simple of mine lovelace dashboard:

          - type: 'custom:swipe-card'
            card_width: 100%
            start_card: 1
            reset_after: 30
            parameters:
              centeredSlides: true
              slidesPerView: 'auto'
              spaceBetween: 8
              pagination:
                  type: 'progressbar'
              navigation:
              keyboard:
                enabled: true
                onlyInViewport: true
              autoHeight: false
              effect: coverflow
            cards:
              - type: picture-entity
                camera_view: live
                entity: camera.ipcamera01
                show_name: false
                show_state: false
                aspect_ratio: 50%
              - type: picture-glance
                title: Front Door
                aspect_ratio: 0%
                camera_image: camera.ipcamera01
                camera_view: auto
                entities: []
                entity: camera.ipcamera01
                tap_action:
                  action: more-info
              - type: 'custom:surveillance-card'
                thumb_interval: 15
                update_interval: 2
                recording_duration: 10
                show_capture_buttons: true
                cameras:
                  - entity: camera.ipcamera01
                    #motion_entity: binary_sensor.front_porch_motion
                  - entity: camera.ipcamera02
                    #motion_entity: binary_sensor.back_yard_motion
                  - entity: camera.ipcamera03
                    #motion_entity: binary_sensor.back_yard_motion
                  - entity: camera.ipcamera04
                    #motion_entity: binary_sensor.back_yard_motion
                  - entity: camera.ipcamera05
                    #motion_entity: binary_sensor.back_yard_motion
              - type: entities
                title: Entities card sample
                entities:
                  - entity: alarm_control_panel.house
                    name: Alarm Panel
                  - device_tracker.mine_tracker
              - type: 'custom:custom-iframe'
                url: 'www.google.it'
            style:
              left: 60%
              top: 40%
              width: 70%
              height: 60%

**Comment by niemyjski** [comment]
Can you take a look into this issue and submit a pr? I believe this card is meant to be used in panel.

**Comment by niemyjski** [comment]
Thanks for reporting this. I'd recommend reporting this on the custom swipe card as it's a limitation with that card and not this project.
