### ISSUE TITLE
Camera updater

### ISSUE THREAD

**Issue by Dario82** [custom-cards/surveillance-card#43]
Hello,
I have a CCTV system outside Hassio's lan.
I've setted the update_interval to 1. 

When I go on panel with surveillance-card, I use 3mbps bandwidth.
But:
- When I leave the panel with surveillance-card, the bandwidth remain the same,
- If I reload the page (with F5) the bandwidth will stop.

Why? Can you help me?
Thank you.

**Comment by niemyjski** [comment]
I'm not sure, perhaps the element still exists and is running in the background. Can you debug this and look into it.

**Comment by niemyjski** [comment]
@Dario82 were you able to solve this?

**Comment by niemyjski** [comment]
I haven't been able to reproduce this, if someone else sees this issue please reopen.

![image](https://user-images.githubusercontent.com/1020579/195985830-701a71f9-8667-4bc6-b1f4-6222952de222.png)
