### ISSUE TITLE
Feature request: Work with WebRTC

### ISSUE THREAD

**Issue by Alfiegerner** [custom-cards/surveillance-card#46]
Hi,

I've found the most reliable and fastest way of viewing my cameras in homeassistant is by using WebRTC custom component: https://github.com/AlexxIT/WebRTC

Would be great to have this work with card.

Thanks!

**Comment by niemyjski** [comment]
Would love a pr for this.

**Comment by niemyjski** [comment]
Thanks for the feature request. I'm going to close this as I don't have resources to implement this and it works fine with my streams, if you'd really like this, please comment/open a pr!
