### ISSUE TITLE
Thumb not showing for motioneye cameras

### ISSUE THREAD

**Issue by JohanEikelenboom** [custom-cards/surveillance-card#52]
Hi,

I have 2 cameras connected to MotionEye and these cameras are added to the surveillance card. This is working like a charm except for the thumbs. I'm not sure what I'm doing wrong. When adding a esphome camera (based on a ESP32), this camera shows up with a thumbnail on the left side. 

Does someone know what I'm doing wrong?

**Comment by niemyjski** [comment]
We use the same api's for both, were you able to figure this out?

**Comment by niemyjski** [comment]
We just use the camera proxy stream https://github.com/custom-cards/surveillance-card/blob/master/surveillance-card.js#L160. there should be no limitation on this... Let me know if you are seeing this with other cards and if there are any errors.
