### ISSUE TITLE
Not working on core-2022.2.9

### ISSUE THREAD

**Issue by Harvsch** [custom-cards/surveillance-card#53]
I installed with HACS and copied the three components as directed in the instructions. It appeared to work briefly, but now only shows one of four cameras and one empty frame. 
The cameras each works correctly and display correctly in a Picture Entity Card. 
```

> type: custom:surveillance-card
> thumb_interval: 15
> update_interval: 1
> recording_duration: 10
> show_capture_buttons: false
> cameras:
>   - entity: camera.porch
>   - entity: camera.driveway
>   - entity: camera.kitchen_bird_cam
>   - entity: camera.entrance

```
The instructions indicate that it should be installed in WWW, but it looks like lovelace is looking in custom components. Copying the files there did not change the proble
![Screenshot from 2022-02-19 19-47-09](https://user-images.githubusercontent.com/29067058/154824131-1e8a22eb-92ec-40d7-8f82-7f6859a65c38.png)
m

**Logs:**
Logger: homeassistant.components.stream.stream.camera.kitchen_bird_cam
Source: components/stream/__init__.py:340
Integration: Stream (documentation, issues)
First occurred: 5:02:20 PM (51 occurrences)
Last logged: 8:34:55 PM

Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@172.24.1.207:554/videoMain

Logger: homeassistant.components.generic.camera
Source: components/generic/camera.py:157
Integration: generic (documentation, issues)
First occurred: 5:02:12 PM (851 occurrences)
Last logged: 8:35:13 PM

Error getting new camera image from Entrance: All connection attempts failed
Error getting new camera image from Porch: Server disconnected without sending a response.
Error getting new camera image from Porch:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:125
Integration: HTTP (documentation, issues)
First occurred: 7:27:03 PM (23 occurrences)
Last logged: 8:33:10 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36)
Login attempt or request with invalid authentication from lenovopc.local (172.24.1.230). (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36)
Login attempt or request with invalid authentication from localhost (127.0.0.1). (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36)

**Comment by niemyjski** [comment]
@Harvsch Please let me know if this is still an issue, looking at the error you sent it looks like the camera blocked the request
