### ISSUE TITLE
Not recognizing Blink Cameras

### ISSUE THREAD

**Issue by cowboysdude** [custom-cards/surveillance-card#55]
![Capture](https://user-images.githubusercontent.com/11013648/170682183-8f121f98-9f67-4d23-8231-d5494730b57c.PNG)

**Comment by cowboysdude** [comment]
`- type: custom:surveillance-card
      title: Surveillance
      icon: mdi:cctv
      panel: true
      cards:
          update_interval: 2
          cameras:
            - entity: camera.blink_back_door
              motion_entity: binary_sensor.blink_back_door_motion_detected
            - entity: camera.blink_livingroom_camera
              motion_entity: binary_sensor.blink_living_room_camera_motion_detected
            - entity: camera.blink_front_doot
              motion_entity: binary_sensor.blink_front_doot_motion_detected`

**Comment by niemyjski** [comment]
We just work off camera entities, we have no limitations on blink. Were you able to solve this?

**Comment by niemyjski** [comment]
I'm closing this until more information is provided. We should support every single camera entity.
