### ISSUE TITLE
Framerate extremely low

### ISSUE THREAD

**Issue by DeaneWheresItAt** [custom-cards/surveillance-card#57]
I have 9 Unifi cameras that i've added to my surveillance card. When i try to view the card, they appear as though they're running at like 1 FPS. It also means that the motion detection change to the right view doesn't change.

Thanks

**Comment by niemyjski** [comment]
I haven't seen this, we just use the camera apis from ha. Do you have this with any other video cards?

**Comment by niemyjski** [comment]
@DeaneWheresItAt I'd recommend trying to set the update interval which is set to 1 second by default. https://github.com/custom-cards/surveillance-card/blob/master/surveillance-card.js#L104 Let us know how that helps. We just pass this along to the camera_proxy_stream api here: https://github.com/custom-cards/surveillance-card/blob/master/surveillance-card.js#L160
