### ISSUE TITLE
Cameras are shown but, but main camera card is blank.

### ISSUE THREAD

**Issue by niemyjski** [custom-cards/surveillance-card#6]
I'm running 83.2 with latest version of this card. I get errors in the console and all I see is a black image where the main image should be.
```
[Error] The operation couldn’t be completed. ( error 0.)
[Error] Cannot load .
```

It looks like the camera_proxy_stream is failing to load but the thumbnails load..

**Comment by robbinonline** [comment]
Same here but only in safari, chrome works fine.

**Comment by niemyjski** [comment]
I'm closing this as I haven't seen this in a really long time. If you are still seeing this @robbinonline please let me know (I use safari too)
