### ISSUE TITLE
Feature request: Hide Thumbnails, set default focus camera

### ISSUE THREAD

**Issue by ekkesa** [custom-cards/surveillance-card#7]
Hi,
First of all - Awesome card! Thank you for this.

Is it possible to hide the thumbnails on the left, and set a default camera view? E.g.

I have a camera which shows a 4x4 grid displaying all my CCTV cameras, and would like to focus to motion and then revert back to grid view afterwards.

Thank you

**Comment by rdariolemes** [comment]
Agree on this!! Will be awesome to have all the cameras in an array and then popup to the main feed of the one detecting motion. After 1 min or so go back to the array.

**Comment by CMaxim77** [comment]
I would love to hide the thumbnail!

**Comment by iantrich** [comment]
You could do this now using [config-template-card](https://github.com/custom-cards/config-template-card). Set up your grid however you like, using stacks or a picture-elements card or whatever and outside of that use the config-template-card to watch for motion changes to match and switch to a picture card with that camera defined as the stream source and then it switches back to your grid when motion not detected

**Comment by niemyjski** [comment]
It sounds like this is already available via @iantrich's comment, for this reason I'm going to close this issue but if someone wants to submit a pr for this, we'll review it and accept it.
