### ISSUE TITLE
Feature request: Set thumbnail size

### ISSUE THREAD

**Issue by BoneheadFraggle** [custom-cards/surveillance-card#9]
I have 10 cameras and I need to scroll down since they don't fit on screen.
It would be nice to set a smaller thumbnail size to fit them all on screen.

**Comment by TheAlphaLaw** [comment]
I second this. I have a few cameras with different resolutions and the thumbnails are far bigger than other cameras. I force all my Lovelace picture entity cards to "- aspect_ratio: 16x9", but cannot resize thumbnails here.

**Comment by niemyjski** [comment]
If you want to submit a PR for this, we'd gladly accept it. I'm going to close this in the near future if there are no takers. I've been using the motion entities to trigger the camera change.
